// <auto-generated />
using System;
using MedicalAppointment.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalAppointment.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210225023_AddDoctorAvailabilityManagement")]
    partial class AddDoctorAvailabilityManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateTime>("AppointmentDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DoctorRespondedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DoctorResponseNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PatientRespondedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PostponeReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PostponeRequestStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("None");

                    b.Property<DateTime?>("PostponeRequestedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProposedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Scheduled");

                    b.HasKey("AppointmentId");

                    b.HasIndex("CancelledByUserId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("Status");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.Clinic", b =>
                {
                    b.Property<Guid>("ClinicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("");

                    b.Property<int?>("AvgNewPatientWaitDays")
                        .HasColumnType("int");

                    b.Property<string>("BookingMethods")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("");

                    b.Property<string>("City")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("CliaNumber")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasDefaultValue("US");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Ein")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<DateOnly?>("FoundedOn")
                        .HasColumnType("date");

                    b.Property<string>("HipaaNoticeVersion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateOnly?>("LastSecurityRiskAssessmentOn")
                        .HasColumnType("date");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("");

                    b.Property<string>("MainEmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("");

                    b.Property<string>("MainPhone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NpiOrganization")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("");

                    b.Property<string>("PatientPortalUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<bool>("SameDayAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<string>("StateLicenseFacility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("");

                    b.Property<int>("SysClinicTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SysOwnershipTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SysSourceSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TaxonomyCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasDefaultValue("");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("America/Chicago");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasDefaultValue("");

                    b.HasKey("ClinicId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SysClinicTypeId");

                    b.HasIndex("SysOwnershipTypeId");

                    b.HasIndex("SysSourceSystemId");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.ClinicAccreditation", b =>
                {
                    b.Property<Guid>("ClinicAccreditationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly?>("EffectiveOn")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SysAccreditationId")
                        .HasColumnType("int");

                    b.HasKey("ClinicAccreditationId");

                    b.HasIndex("SysAccreditationId");

                    b.HasIndex("ClinicId", "SysAccreditationId")
                        .IsUnique();

                    b.ToTable("ClinicAccreditations");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.ClinicInsurancePlan", b =>
                {
                    b.Property<Guid>("ClinicInsurancePlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsInNetwork")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PayerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("ClinicInsurancePlanId");

                    b.HasIndex("ClinicId", "PayerName", "PlanName")
                        .IsUnique();

                    b.ToTable("ClinicInsurancePlans");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.ClinicOperatingHour", b =>
                {
                    b.Property<Guid>("ClinicOperatingHourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("CloseTime")
                        .HasColumnType("time");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<bool>("IsClosed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<TimeSpan?>("OpenTime")
                        .HasColumnType("time");

                    b.HasKey("ClinicOperatingHourId");

                    b.HasIndex("ClinicId", "DayOfWeek")
                        .IsUnique();

                    b.ToTable("ClinicOperatingHours", t =>
                        {
                            t.HasCheckConstraint("CK_ClinicOperatingHours_DayOfWeek", "[DayOfWeek] >= 0 AND [DayOfWeek] <= 6");
                        });
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.ClinicService", b =>
                {
                    b.Property<Guid>("ClinicServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTelehealthAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SysOperationId")
                        .HasColumnType("int");

                    b.HasKey("ClinicServiceId");

                    b.HasIndex("SysOperationId");

                    b.HasIndex("ClinicId", "SysOperationId")
                        .IsUnique();

                    b.ToTable("ClinicServices");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.DoctorAvailabilityBreak", b =>
                {
                    b.Property<Guid>("DoctorAvailabilityBreakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("DoctorAvailabilityBreakId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("DoctorId", "DayOfWeek", "StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("DoctorAvailabilityBreaks", t =>
                        {
                            t.HasCheckConstraint("CK_DoctorAvailabilityBreaks_DayOfWeek", "[DayOfWeek] >= 0 AND [DayOfWeek] <= 6");

                            t.HasCheckConstraint("CK_DoctorAvailabilityBreaks_TimeRange", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.DoctorAvailabilityOverride", b =>
                {
                    b.Property<Guid>("DoctorAvailabilityOverrideId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("DoctorAvailabilityOverrideId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("DoctorId", "Date", "IsAvailable", "StartTime", "EndTime")
                        .IsUnique()
                        .HasFilter("[StartTime] IS NOT NULL AND [EndTime] IS NOT NULL");

                    b.ToTable("DoctorAvailabilityOverrides", t =>
                        {
                            t.HasCheckConstraint("CK_DoctorAvailabilityOverrides_TimeRange", "[StartTime] IS NULL OR [EndTime] IS NULL OR [StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.DoctorAvailabilityWindow", b =>
                {
                    b.Property<Guid>("DoctorAvailabilityWindowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("DoctorAvailabilityWindowId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("DoctorId", "DayOfWeek", "StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("DoctorAvailabilityWindows", t =>
                        {
                            t.HasCheckConstraint("CK_DoctorAvailabilityWindows_DayOfWeek", "[DayOfWeek] >= 0 AND [DayOfWeek] <= 6");

                            t.HasCheckConstraint("CK_DoctorAvailabilityWindows_TimeRange", "[StartTime] < [EndTime]");
                        });
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.Person", b =>
                {
                    b.Property<Guid>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalIdentifier")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("PersonId");

                    b.HasIndex("PersonalIdentifier")
                        .IsUnique();

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysAccreditation", b =>
                {
                    b.Property<int>("SysAccreditationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysAccreditationId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("SysAccreditationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SysAccreditations");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysClinicType", b =>
                {
                    b.Property<int>("SysClinicTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysClinicTypeId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("SysClinicTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SysClinicTypes");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysOperation", b =>
                {
                    b.Property<int>("SysOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysOperationId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SysOperationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SysOperations");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysOwnershipType", b =>
                {
                    b.Property<int>("SysOwnershipTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysOwnershipTypeId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("SysOwnershipTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SysOwnershipTypes");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysSourceSystem", b =>
                {
                    b.Property<int>("SysSourceSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysSourceSystemId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("SysSourceSystemId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SysSourceSystems");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SysRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PersonId");

                    b.HasIndex("SysRoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SysRole", b =>
                {
                    b.Property<Guid>("SysRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SysRoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SysRoles");
                });

            modelBuilder.Entity("Appointment", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MedicalAppointment.Domain.Models.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAppointment.Domain.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAppointment.Domain.Models.User", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.Clinic", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.SysClinicType", "SysClinicType")
                        .WithMany("Clinics")
                        .HasForeignKey("SysClinicTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAppointment.Domain.Models.SysOwnershipType", "SysOwnershipType")
                        .WithMany("Clinics")
                        .HasForeignKey("SysOwnershipTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAppointment.Domain.Models.SysSourceSystem", "SysSourceSystem")
                        .WithMany("Clinics")
                        .HasForeignKey("SysSourceSystemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SysClinicType");

                    b.Navigation("SysOwnershipType");

                    b.Navigation("SysSourceSystem");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.ClinicAccreditation", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.Clinic", "Clinic")
                        .WithMany("Accreditations")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalAppointment.Domain.Models.SysAccreditation", "SysAccreditation")
                        .WithMany("ClinicAccreditations")
                        .HasForeignKey("SysAccreditationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("SysAccreditation");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.ClinicInsurancePlan", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.Clinic", "Clinic")
                        .WithMany("InsurancePlans")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.ClinicOperatingHour", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.Clinic", "Clinic")
                        .WithMany("OperatingHours")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.ClinicService", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.Clinic", "Clinic")
                        .WithMany("Services")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalAppointment.Domain.Models.SysOperation", "SysOperation")
                        .WithMany("ClinicServices")
                        .HasForeignKey("SysOperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("SysOperation");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.DoctorAvailabilityBreak", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.DoctorAvailabilityOverride", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.DoctorAvailabilityWindow", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.User", b =>
                {
                    b.HasOne("MedicalAppointment.Domain.Models.Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MedicalAppointment.Domain.Models.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SysRole", "SysRole")
                        .WithMany("Users")
                        .HasForeignKey("SysRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Person");

                    b.Navigation("SysRole");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.Clinic", b =>
                {
                    b.Navigation("Accreditations");

                    b.Navigation("InsurancePlans");

                    b.Navigation("OperatingHours");

                    b.Navigation("Services");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysAccreditation", b =>
                {
                    b.Navigation("ClinicAccreditations");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysClinicType", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysOperation", b =>
                {
                    b.Navigation("ClinicServices");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysOwnershipType", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("MedicalAppointment.Domain.Models.SysSourceSystem", b =>
                {
                    b.Navigation("Clinics");
                });

            modelBuilder.Entity("SysRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
